### ISSUE TITLE
Secrets exposed

### ISSUE THREAD

**Issue by constantins2001** [StephenWelch/mc-miner#1]
Hi Stephen,
I wanted to notify you that you are leaking your Minecraft Username:Password configuration in [this file](https://github.com/StephenWelch/mc-miner/blob/master/main.js#L77). <br/>
I'd recommend changing it and to not commit secrets to Git repositories in the future :)

**Comment by constantins2001** [comment]
@StephenWelch PING

**Comment by StephenWelch** [comment]
Hey, thanks for the heads up. Meant to make this repo private but must've forgot.
